// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package dbgen

import (
	"context"
)

const countActivitiesByActor = `-- name: CountActivitiesByActor :one
SELECT COUNT(*) FROM activities
WHERE actor_id = ?
`

func (q *Queries) CountActivitiesByActor(ctx context.Context, actorID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivitiesByActor, actorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activities (actor_id, actor_type, action, object_id, object_type, target_id, target_type, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertActivityParams struct {
	ActorID    string  `json:"actor_id"`
	ActorType  string  `json:"actor_type"`
	Action     string  `json:"action"`
	ObjectID   string  `json:"object_id"`
	ObjectType string  `json:"object_type"`
	TargetID   *string `json:"target_id"`
	TargetType *string `json:"target_type"`
	Metadata   *string `json:"metadata"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.ObjectID,
		arg.ObjectType,
		arg.TargetID,
		arg.TargetType,
		arg.Metadata,
	)
	return err
}

const listActivitiesByActor = `-- name: ListActivitiesByActor :many
SELECT id, actor_id, actor_type, "action", object_id, object_type, target_id, target_type, metadata, created_at FROM activities
WHERE actor_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListActivitiesByActorParams struct {
	ActorID string `json:"actor_id"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) ListActivitiesByActor(ctx context.Context, arg ListActivitiesByActorParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByActor, arg.ActorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.ObjectID,
			&i.ObjectType,
			&i.TargetID,
			&i.TargetType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesByObject = `-- name: ListActivitiesByObject :many
SELECT id, actor_id, actor_type, "action", object_id, object_type, target_id, target_type, metadata, created_at FROM activities
WHERE object_type = ? AND object_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListActivitiesByObjectParams struct {
	ObjectType string `json:"object_type"`
	ObjectID   string `json:"object_id"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) ListActivitiesByObject(ctx context.Context, arg ListActivitiesByObjectParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByObject, arg.ObjectType, arg.ObjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.ObjectID,
			&i.ObjectType,
			&i.TargetID,
			&i.TargetType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesByTarget = `-- name: ListActivitiesByTarget :many
SELECT id, actor_id, actor_type, "action", object_id, object_type, target_id, target_type, metadata, created_at FROM activities
WHERE target_type = ? AND target_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListActivitiesByTargetParams struct {
	TargetType *string `json:"target_type"`
	TargetID   *string `json:"target_id"`
	Limit      int64   `json:"limit"`
}

func (q *Queries) ListActivitiesByTarget(ctx context.Context, arg ListActivitiesByTargetParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByTarget, arg.TargetType, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.ObjectID,
			&i.ObjectType,
			&i.TargetID,
			&i.TargetType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
