// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package dbgen

import (
	"context"
)

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activities (actor_id, actor_type, action, metadata)
VALUES (?, ?, ?, ?)
`

type InsertActivityParams struct {
	ActorID   string  `json:"actor_id"`
	ActorType string  `json:"actor_type"`
	Action    string  `json:"action"`
	Metadata  *string `json:"metadata"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.Metadata,
	)
	return err
}

const listActivitiesByActor = `-- name: ListActivitiesByActor :many
SELECT id, actor_id, actor_type, "action", metadata, created_at FROM activities
WHERE actor_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListActivitiesByActorParams struct {
	ActorID string `json:"actor_id"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) ListActivitiesByActor(ctx context.Context, arg ListActivitiesByActorParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByActor, arg.ActorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
