// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package dbgen

import (
	"context"
)

const addChatMember = `-- name: AddChatMember :exec
INSERT OR IGNORE INTO chat_members (chat_id, user_email, user_id)
VALUES (?, ?, ?)
`

type AddChatMemberParams struct {
	ChatID    int64  `json:"chat_id"`
	UserEmail string `json:"user_email"`
	UserID    string `json:"user_id"`
}

func (q *Queries) AddChatMember(ctx context.Context, arg AddChatMemberParams) error {
	_, err := q.db.ExecContext(ctx, addChatMember, arg.ChatID, arg.UserEmail, arg.UserID)
	return err
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats (owner_id, title)
VALUES (?, ?)
RETURNING created_at, id, owner_id, title, updated_at
`

type CreateChatParams struct {
	OwnerID string `json:"owner_id"`
	Title   string `json:"title"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, arg.OwnerID, arg.Title)
	var i Chat
	err := row.Scan(
		&i.CreatedAt,
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id, content, sender_email, sender_id)
VALUES (?, ?, ?, ?)
RETURNING chat_id, content, created_at, id, sender_email, sender_id
`

type CreateMessageParams struct {
	ChatID      int64  `json:"chat_id"`
	Content     string `json:"content"`
	SenderEmail string `json:"sender_email"`
	SenderID    string `json:"sender_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ChatID,
		arg.Content,
		arg.SenderEmail,
		arg.SenderID,
	)
	var i Message
	err := row.Scan(
		&i.ChatID,
		&i.Content,
		&i.CreatedAt,
		&i.ID,
		&i.SenderEmail,
		&i.SenderID,
	)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats WHERE id = ?
`

func (q *Queries) DeleteChat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChat, id)
	return err
}

const getChat = `-- name: GetChat :one
SELECT created_at, id, owner_id, title, updated_at FROM chats WHERE id = ?
`

func (q *Queries) GetChat(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.CreatedAt,
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestMessage = `-- name: GetLatestMessage :one
SELECT chat_id, content, created_at, id, sender_email, sender_id FROM messages WHERE chat_id = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestMessage(ctx context.Context, chatID int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, getLatestMessage, chatID)
	var i Message
	err := row.Scan(
		&i.ChatID,
		&i.Content,
		&i.CreatedAt,
		&i.ID,
		&i.SenderEmail,
		&i.SenderID,
	)
	return i, err
}

const isChatMember = `-- name: IsChatMember :one
SELECT COUNT(*) > 0 AS is_member FROM chat_members WHERE chat_id = ? AND user_id = ?
`

type IsChatMemberParams struct {
	ChatID int64  `json:"chat_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isChatMember, arg.ChatID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listChatMembers = `-- name: ListChatMembers :many
SELECT chat_id, created_at, user_email, user_id FROM chat_members WHERE chat_id = ? ORDER BY created_at
`

func (q *Queries) ListChatMembers(ctx context.Context, chatID int64) ([]ChatMember, error) {
	rows, err := q.db.QueryContext(ctx, listChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMember{}
	for rows.Next() {
		var i ChatMember
		if err := rows.Scan(
			&i.ChatID,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatsByUser = `-- name: ListChatsByUser :many
SELECT c.created_at, c.id, c.owner_id, c.title, c.updated_at FROM chats c
JOIN chat_members cm ON cm.chat_id = c.id
WHERE cm.user_id = ?
ORDER BY c.updated_at DESC
`

func (q *Queries) ListChatsByUser(ctx context.Context, userID string) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, listChatsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chat{}
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.CreatedAt,
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT chat_id, content, created_at, id, sender_email, sender_id FROM messages WHERE chat_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListMessages(ctx context.Context, chatID int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ChatID,
			&i.Content,
			&i.CreatedAt,
			&i.ID,
			&i.SenderEmail,
			&i.SenderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchChat = `-- name: TouchChat :exec
UPDATE chats SET updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchChat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchChat, id)
	return err
}

const updateChatTitle = `-- name: UpdateChatTitle :exec
UPDATE chats SET title = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateChatTitleParams struct {
	Title string `json:"title"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateChatTitle(ctx context.Context, arg UpdateChatTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateChatTitle, arg.Title, arg.ID)
	return err
}
