// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package dbgen

import (
	"context"
)

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats WHERE id = ? AND user_id = ?
`

type DeleteChatParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteChat(ctx context.Context, arg DeleteChatParams) error {
	_, err := q.db.ExecContext(ctx, deleteChat, arg.ID, arg.UserID)
	return err
}

const getChat = `-- name: GetChat :one
SELECT id, title, user_id, created_at, updated_at FROM chats
WHERE id = ? AND user_id = ?
`

type GetChatParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetChat(ctx context.Context, arg GetChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, arg.ID, arg.UserID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChat = `-- name: InsertChat :exec
INSERT INTO chats (id, title, user_id)
VALUES (?, ?, ?)
`

type InsertChatParams struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	UserID string `json:"user_id"`
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) error {
	_, err := q.db.ExecContext(ctx, insertChat, arg.ID, arg.Title, arg.UserID)
	return err
}

const listChatsByUser = `-- name: ListChatsByUser :many
SELECT id, title, user_id, created_at, updated_at FROM chats
WHERE user_id = ?
ORDER BY updated_at DESC
LIMIT ?
`

type ListChatsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListChatsByUser(ctx context.Context, arg ListChatsByUserParams) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, listChatsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chat{}
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatTimestamp = `-- name: UpdateChatTimestamp :exec
UPDATE chats SET updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateChatTimestamp(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateChatTimestamp, id)
	return err
}

const updateChatTitle = `-- name: UpdateChatTitle :exec
UPDATE chats SET title = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateChatTitleParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateChatTitle(ctx context.Context, arg UpdateChatTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateChatTitle, arg.Title, arg.ID)
	return err
}
