// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_access.sql

package dbgen

import (
	"context"
)

const deleteClientAccessByClientID = `-- name: DeleteClientAccessByClientID :exec
DELETE FROM client_access WHERE client_id = ?
`

func (q *Queries) DeleteClientAccessByClientID(ctx context.Context, clientID int64) error {
	_, err := q.db.ExecContext(ctx, deleteClientAccessByClientID, clientID)
	return err
}

const insertClientAccess = `-- name: InsertClientAccess :exec
INSERT INTO client_access (client_id, domain, email) VALUES (?, ?, ?)
`

type InsertClientAccessParams struct {
	ClientID int64  `json:"client_id"`
	Domain   string `json:"domain"`
	Email    string `json:"email"`
}

func (q *Queries) InsertClientAccess(ctx context.Context, arg InsertClientAccessParams) error {
	_, err := q.db.ExecContext(ctx, insertClientAccess, arg.ClientID, arg.Domain, arg.Email)
	return err
}

const listOidcClientsByAccess = `-- name: ListOidcClientsByAccess :many
SELECT DISTINCT c.id, c.client_id, c.client_secret, c.name, c.redirect_uris, c.post_logout_redirect_uris, c.application_type, c.auth_method, c.response_types, c.grant_types, c.access_token_type, c.scopes, c.created_by, c.archived_at, c.created_at, c.updated_at, c.allowed_domain, c.allowed_emails FROM oidc_clients c
JOIN client_access ca ON ca.client_id = c.id
WHERE (ca.email = ? OR ca.domain = ?)
AND c.archived_at IS NULL
ORDER BY c.created_at DESC
`

type ListOidcClientsByAccessParams struct {
	Email  string `json:"email"`
	Domain string `json:"domain"`
}

func (q *Queries) ListOidcClientsByAccess(ctx context.Context, arg ListOidcClientsByAccessParams) ([]OidcClient, error) {
	rows, err := q.db.QueryContext(ctx, listOidcClientsByAccess, arg.Email, arg.Domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcClient{}
	for rows.Next() {
		var i OidcClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecret,
			&i.Name,
			&i.RedirectUris,
			&i.PostLogoutRedirectUris,
			&i.ApplicationType,
			&i.AuthMethod,
			&i.ResponseTypes,
			&i.GrantTypes,
			&i.AccessTokenType,
			&i.Scopes,
			&i.CreatedBy,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AllowedDomain,
			&i.AllowedEmails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
