// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package dbgen

import (
	"context"
)

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (chat_id, content, role)
VALUES (?, ?, ?)
`

type InsertMessageParams struct {
	ChatID  string `json:"chat_id"`
	Content string `json:"content"`
	Role    string `json:"role"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage, arg.ChatID, arg.Content, arg.Role)
	return err
}

const listMessagesByChat = `-- name: ListMessagesByChat :many
SELECT id, chat_id, content, role, created_at FROM messages
WHERE chat_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByChat(ctx context.Context, chatID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Content,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
