// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Activity struct {
	ID         int64     `json:"id"`
	ActorID    string    `json:"actor_id"`
	ActorType  string    `json:"actor_type"`
	Action     string    `json:"action"`
	ObjectID   string    `json:"object_id"`
	ObjectType string    `json:"object_type"`
	TargetID   *string   `json:"target_id"`
	TargetType *string   `json:"target_type"`
	Metadata   *string   `json:"metadata"`
	CreatedAt  time.Time `json:"created_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}
