// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Activity struct {
	ID         int64     `json:"id"`
	ActorID    string    `json:"actor_id"`
	ActorType  string    `json:"actor_type"`
	Action     string    `json:"action"`
	ObjectID   string    `json:"object_id"`
	ObjectType string    `json:"object_type"`
	TargetID   *string   `json:"target_id"`
	TargetType *string   `json:"target_type"`
	Metadata   *string   `json:"metadata"`
	CreatedAt  time.Time `json:"created_at"`
}

type ClientAccess struct {
	ClientID int64  `json:"client_id"`
	Domain   string `json:"domain"`
	Email    string `json:"email"`
}

type OauthToken struct {
	ID           int64      `json:"id"`
	AccessToken  string     `json:"access_token"`
	ExpiresAt    *time.Time `json:"expires_at"`
	Level        string     `json:"level"`
	Provider     string     `json:"provider"`
	RefreshToken string     `json:"refresh_token"`
	Scopes       string     `json:"scopes"`
	Service      string     `json:"service"`
	Subject      string     `json:"subject"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	ClientID     string     `json:"client_id"`
}

type OidcAccessToken struct {
	ID            string    `json:"id"`
	ApplicationID string    `json:"application_id"`
	Subject       string    `json:"subject"`
	Audience      string    `json:"audience"`
	Scopes        string    `json:"scopes"`
	ExpiresAt     time.Time `json:"expires_at"`
	CreatedAt     time.Time `json:"created_at"`
}

type OidcAuthRequest struct {
	ID                  string     `json:"id"`
	ClientID            string     `json:"client_id"`
	RedirectUri         string     `json:"redirect_uri"`
	Scopes              string     `json:"scopes"`
	State               string     `json:"state"`
	Nonce               string     `json:"nonce"`
	ResponseType        string     `json:"response_type"`
	CodeChallenge       string     `json:"code_challenge"`
	CodeChallengeMethod string     `json:"code_challenge_method"`
	Subject             string     `json:"subject"`
	UserEmail           string     `json:"user_email"`
	AuthTime            *time.Time `json:"auth_time"`
	Done                int64      `json:"done"`
	CreatedAt           time.Time  `json:"created_at"`
	LoginHint           string     `json:"login_hint"`
}

type OidcClient struct {
	ID                     int64      `json:"id"`
	ClientID               string     `json:"client_id"`
	ClientSecret           string     `json:"client_secret"`
	Name                   string     `json:"name"`
	RedirectUris           string     `json:"redirect_uris"`
	PostLogoutRedirectUris string     `json:"post_logout_redirect_uris"`
	ApplicationType        string     `json:"application_type"`
	AuthMethod             string     `json:"auth_method"`
	ResponseTypes          string     `json:"response_types"`
	GrantTypes             string     `json:"grant_types"`
	AccessTokenType        string     `json:"access_token_type"`
	Scopes                 string     `json:"scopes"`
	CreatedBy              string     `json:"created_by"`
	ArchivedAt             *time.Time `json:"archived_at"`
	CreatedAt              time.Time  `json:"created_at"`
	UpdatedAt              time.Time  `json:"updated_at"`
	AllowedDomain          string     `json:"allowed_domain"`
	AllowedEmails          string     `json:"allowed_emails"`
}

type OidcCode struct {
	Code          string    `json:"code"`
	AuthRequestID string    `json:"auth_request_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type OidcRefreshToken struct {
	ID            string    `json:"id"`
	Token         string    `json:"token"`
	AuthTime      time.Time `json:"auth_time"`
	Audience      string    `json:"audience"`
	Subject       string    `json:"subject"`
	ApplicationID string    `json:"application_id"`
	Scopes        string    `json:"scopes"`
	ExpiresAt     time.Time `json:"expires_at"`
	CreatedAt     time.Time `json:"created_at"`
}

type Session struct {
	ID        string    `json:"id"`
	Subject   string    `json:"subject"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Provider  string    `json:"provider"`
}

type UserSetting struct {
	Subject   string    `json:"subject"`
	Settings  string    `json:"settings"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
