// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_tokens.sql

package dbgen

import (
	"context"
	"time"
)

const deleteOAuthToken = `-- name: DeleteOAuthToken :exec
DELETE FROM oauth_tokens
WHERE user_id = ? AND service = ? AND level = ?
`

type DeleteOAuthTokenParams struct {
	UserID  string `json:"user_id"`
	Service string `json:"service"`
	Level   string `json:"level"`
}

func (q *Queries) DeleteOAuthToken(ctx context.Context, arg DeleteOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthToken, arg.UserID, arg.Service, arg.Level)
	return err
}

const deleteOAuthTokensByUserAndService = `-- name: DeleteOAuthTokensByUserAndService :exec
DELETE FROM oauth_tokens
WHERE user_id = ? AND service = ?
`

type DeleteOAuthTokensByUserAndServiceParams struct {
	UserID  string `json:"user_id"`
	Service string `json:"service"`
}

func (q *Queries) DeleteOAuthTokensByUserAndService(ctx context.Context, arg DeleteOAuthTokensByUserAndServiceParams) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthTokensByUserAndService, arg.UserID, arg.Service)
	return err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, access_token, expires_at, level, provider, refresh_token, scopes, service, user_id, created_at, updated_at, client_id FROM oauth_tokens
WHERE user_id = ? AND service = ? AND level = ?
`

type GetOAuthTokenParams struct {
	UserID  string `json:"user_id"`
	Service string `json:"service"`
	Level   string `json:"level"`
}

func (q *Queries) GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, getOAuthToken, arg.UserID, arg.Service, arg.Level)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.Level,
		&i.Provider,
		&i.RefreshToken,
		&i.Scopes,
		&i.Service,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientID,
	)
	return i, err
}

const listOAuthTokensByUser = `-- name: ListOAuthTokensByUser :many
SELECT id, access_token, expires_at, level, provider, refresh_token, scopes, service, user_id, created_at, updated_at, client_id FROM oauth_tokens
WHERE user_id = ?
ORDER BY service, level
`

func (q *Queries) ListOAuthTokensByUser(ctx context.Context, userID string) ([]OauthToken, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthToken{}
	for rows.Next() {
		var i OauthToken
		if err := rows.Scan(
			&i.ID,
			&i.AccessToken,
			&i.ExpiresAt,
			&i.Level,
			&i.Provider,
			&i.RefreshToken,
			&i.Scopes,
			&i.Service,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOAuthToken = `-- name: UpsertOAuthToken :exec
INSERT INTO oauth_tokens (access_token, client_id, expires_at, level, provider, refresh_token, scopes, service, user_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, service, level) DO UPDATE SET
    access_token = excluded.access_token,
    client_id = excluded.client_id,
    expires_at = excluded.expires_at,
    refresh_token = excluded.refresh_token,
    scopes = excluded.scopes,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertOAuthTokenParams struct {
	AccessToken  string     `json:"access_token"`
	ClientID     string     `json:"client_id"`
	ExpiresAt    *time.Time `json:"expires_at"`
	Level        string     `json:"level"`
	Provider     string     `json:"provider"`
	RefreshToken string     `json:"refresh_token"`
	Scopes       string     `json:"scopes"`
	Service      string     `json:"service"`
	UserID       string     `json:"user_id"`
}

func (q *Queries) UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertOAuthToken,
		arg.AccessToken,
		arg.ClientID,
		arg.ExpiresAt,
		arg.Level,
		arg.Provider,
		arg.RefreshToken,
		arg.Scopes,
		arg.Service,
		arg.UserID,
	)
	return err
}
