// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_clients.sql

package dbgen

import (
	"context"
)

const archiveOidcClient = `-- name: ArchiveOidcClient :exec
UPDATE oidc_clients
SET archived_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND archived_at IS NULL
`

func (q *Queries) ArchiveOidcClient(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveOidcClient, id)
	return err
}

const countOidcClients = `-- name: CountOidcClients :one
SELECT COUNT(*) FROM oidc_clients
WHERE archived_at IS NULL
`

func (q *Queries) CountOidcClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOidcClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOidcClient = `-- name: GetOidcClient :one
SELECT id, client_id, client_secret, name, redirect_uris, post_logout_redirect_uris, application_type, auth_method, response_types, grant_types, access_token_type, scopes, created_by, archived_at, created_at, updated_at FROM oidc_clients
WHERE id = ? AND archived_at IS NULL
`

func (q *Queries) GetOidcClient(ctx context.Context, id int64) (OidcClient, error) {
	row := q.db.QueryRowContext(ctx, getOidcClient, id)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.ApplicationType,
		&i.AuthMethod,
		&i.ResponseTypes,
		&i.GrantTypes,
		&i.AccessTokenType,
		&i.Scopes,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOidcClientByClientID = `-- name: GetOidcClientByClientID :one
SELECT id, client_id, client_secret, name, redirect_uris, post_logout_redirect_uris, application_type, auth_method, response_types, grant_types, access_token_type, scopes, created_by, archived_at, created_at, updated_at FROM oidc_clients
WHERE client_id = ? AND archived_at IS NULL
`

func (q *Queries) GetOidcClientByClientID(ctx context.Context, clientID string) (OidcClient, error) {
	row := q.db.QueryRowContext(ctx, getOidcClientByClientID, clientID)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.ApplicationType,
		&i.AuthMethod,
		&i.ResponseTypes,
		&i.GrantTypes,
		&i.AccessTokenType,
		&i.Scopes,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOidcClient = `-- name: InsertOidcClient :one
INSERT INTO oidc_clients (client_id, client_secret, name, redirect_uris, scopes, created_by)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, client_id, client_secret, name, redirect_uris, post_logout_redirect_uris, application_type, auth_method, response_types, grant_types, access_token_type, scopes, created_by, archived_at, created_at, updated_at
`

type InsertOidcClientParams struct {
	ClientID     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Name         string `json:"name"`
	RedirectUris string `json:"redirect_uris"`
	Scopes       string `json:"scopes"`
	CreatedBy    string `json:"created_by"`
}

func (q *Queries) InsertOidcClient(ctx context.Context, arg InsertOidcClientParams) (OidcClient, error) {
	row := q.db.QueryRowContext(ctx, insertOidcClient,
		arg.ClientID,
		arg.ClientSecret,
		arg.Name,
		arg.RedirectUris,
		arg.Scopes,
		arg.CreatedBy,
	)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.ApplicationType,
		&i.AuthMethod,
		&i.ResponseTypes,
		&i.GrantTypes,
		&i.AccessTokenType,
		&i.Scopes,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOidcClientFull = `-- name: InsertOidcClientFull :one
INSERT INTO oidc_clients (client_id, client_secret, name, redirect_uris, scopes, auth_method, grant_types, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, client_id, client_secret, name, redirect_uris, post_logout_redirect_uris, application_type, auth_method, response_types, grant_types, access_token_type, scopes, created_by, archived_at, created_at, updated_at
`

type InsertOidcClientFullParams struct {
	ClientID     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Name         string `json:"name"`
	RedirectUris string `json:"redirect_uris"`
	Scopes       string `json:"scopes"`
	AuthMethod   string `json:"auth_method"`
	GrantTypes   string `json:"grant_types"`
	CreatedBy    string `json:"created_by"`
}

func (q *Queries) InsertOidcClientFull(ctx context.Context, arg InsertOidcClientFullParams) (OidcClient, error) {
	row := q.db.QueryRowContext(ctx, insertOidcClientFull,
		arg.ClientID,
		arg.ClientSecret,
		arg.Name,
		arg.RedirectUris,
		arg.Scopes,
		arg.AuthMethod,
		arg.GrantTypes,
		arg.CreatedBy,
	)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Name,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.ApplicationType,
		&i.AuthMethod,
		&i.ResponseTypes,
		&i.GrantTypes,
		&i.AccessTokenType,
		&i.Scopes,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOidcClients = `-- name: ListOidcClients :many
SELECT id, client_id, client_secret, name, redirect_uris, post_logout_redirect_uris, application_type, auth_method, response_types, grant_types, access_token_type, scopes, created_by, archived_at, created_at, updated_at FROM oidc_clients
WHERE archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListOidcClients(ctx context.Context) ([]OidcClient, error) {
	rows, err := q.db.QueryContext(ctx, listOidcClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcClient{}
	for rows.Next() {
		var i OidcClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecret,
			&i.Name,
			&i.RedirectUris,
			&i.PostLogoutRedirectUris,
			&i.ApplicationType,
			&i.AuthMethod,
			&i.ResponseTypes,
			&i.GrantTypes,
			&i.AccessTokenType,
			&i.Scopes,
			&i.CreatedBy,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOidcClient = `-- name: UpdateOidcClient :exec
UPDATE oidc_clients
SET name = ?, redirect_uris = ?, scopes = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND archived_at IS NULL
`

type UpdateOidcClientParams struct {
	Name         string `json:"name"`
	RedirectUris string `json:"redirect_uris"`
	Scopes       string `json:"scopes"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateOidcClient(ctx context.Context, arg UpdateOidcClientParams) error {
	_, err := q.db.ExecContext(ctx, updateOidcClient,
		arg.Name,
		arg.RedirectUris,
		arg.Scopes,
		arg.ID,
	)
	return err
}
