// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_provider.sql

package dbgen

import (
	"context"
	"time"
)

const completeAuthRequest = `-- name: CompleteAuthRequest :exec
UPDATE oidc_auth_requests
SET subject = ?, user_email = ?, auth_time = CURRENT_TIMESTAMP, done = 1
WHERE id = ?
`

type CompleteAuthRequestParams struct {
	Subject   string `json:"subject"`
	UserEmail string `json:"user_email"`
	ID        string `json:"id"`
}

func (q *Queries) CompleteAuthRequest(ctx context.Context, arg CompleteAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, completeAuthRequest, arg.Subject, arg.UserEmail, arg.ID)
	return err
}

const deleteAccessToken = `-- name: DeleteAccessToken :exec
DELETE FROM oidc_access_tokens WHERE id = ?
`

func (q *Queries) DeleteAccessToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAccessToken, id)
	return err
}

const deleteAccessTokensBySubject = `-- name: DeleteAccessTokensBySubject :exec
DELETE FROM oidc_access_tokens WHERE subject = ? AND application_id = ?
`

type DeleteAccessTokensBySubjectParams struct {
	Subject       string `json:"subject"`
	ApplicationID string `json:"application_id"`
}

func (q *Queries) DeleteAccessTokensBySubject(ctx context.Context, arg DeleteAccessTokensBySubjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccessTokensBySubject, arg.Subject, arg.ApplicationID)
	return err
}

const deleteAuthCode = `-- name: DeleteAuthCode :exec
DELETE FROM oidc_codes WHERE code = ?
`

func (q *Queries) DeleteAuthCode(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthCode, code)
	return err
}

const deleteAuthCodesByRequestID = `-- name: DeleteAuthCodesByRequestID :exec
DELETE FROM oidc_codes WHERE auth_request_id = ?
`

func (q *Queries) DeleteAuthCodesByRequestID(ctx context.Context, authRequestID string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthCodesByRequestID, authRequestID)
	return err
}

const deleteAuthRequest = `-- name: DeleteAuthRequest :exec
DELETE FROM oidc_auth_requests WHERE id = ?
`

func (q *Queries) DeleteAuthRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthRequest, id)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM oidc_refresh_tokens WHERE id = ?
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, id)
	return err
}

const deleteRefreshTokenByToken = `-- name: DeleteRefreshTokenByToken :exec
DELETE FROM oidc_refresh_tokens WHERE token = ?
`

func (q *Queries) DeleteRefreshTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokenByToken, token)
	return err
}

const deleteRefreshTokensBySubject = `-- name: DeleteRefreshTokensBySubject :exec
DELETE FROM oidc_refresh_tokens WHERE subject = ? AND application_id = ?
`

type DeleteRefreshTokensBySubjectParams struct {
	Subject       string `json:"subject"`
	ApplicationID string `json:"application_id"`
}

func (q *Queries) DeleteRefreshTokensBySubject(ctx context.Context, arg DeleteRefreshTokensBySubjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensBySubject, arg.Subject, arg.ApplicationID)
	return err
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT id, application_id, subject, audience, scopes, expires_at, created_at FROM oidc_access_tokens
WHERE id = ? AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetAccessToken(ctx context.Context, id string) (OidcAccessToken, error) {
	row := q.db.QueryRowContext(ctx, getAccessToken, id)
	var i OidcAccessToken
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Subject,
		&i.Audience,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthRequest = `-- name: GetAuthRequest :one
SELECT id, client_id, redirect_uri, scopes, state, nonce, response_type, code_challenge, code_challenge_method, subject, user_email, auth_time, done, created_at FROM oidc_auth_requests WHERE id = ?
`

func (q *Queries) GetAuthRequest(ctx context.Context, id string) (OidcAuthRequest, error) {
	row := q.db.QueryRowContext(ctx, getAuthRequest, id)
	var i OidcAuthRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.ResponseType,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Subject,
		&i.UserEmail,
		&i.AuthTime,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthRequestByCode = `-- name: GetAuthRequestByCode :one
SELECT r.id, r.client_id, r.redirect_uri, r.scopes, r.state, r.nonce, r.response_type, r.code_challenge, r.code_challenge_method, r.subject, r.user_email, r.auth_time, r.done, r.created_at FROM oidc_auth_requests r
JOIN oidc_codes c ON c.auth_request_id = r.id
WHERE c.code = ?
`

func (q *Queries) GetAuthRequestByCode(ctx context.Context, code string) (OidcAuthRequest, error) {
	row := q.db.QueryRowContext(ctx, getAuthRequestByCode, code)
	var i OidcAuthRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.ResponseType,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Subject,
		&i.UserEmail,
		&i.AuthTime,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAuthRequestBySubjectAndClient = `-- name: GetLatestAuthRequestBySubjectAndClient :one
SELECT id, client_id, redirect_uri, scopes, state, nonce, response_type, code_challenge, code_challenge_method, subject, user_email, auth_time, done, created_at FROM oidc_auth_requests
WHERE subject = ? AND client_id = ? AND done = 1
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestAuthRequestBySubjectAndClientParams struct {
	Subject  string `json:"subject"`
	ClientID string `json:"client_id"`
}

func (q *Queries) GetLatestAuthRequestBySubjectAndClient(ctx context.Context, arg GetLatestAuthRequestBySubjectAndClientParams) (OidcAuthRequest, error) {
	row := q.db.QueryRowContext(ctx, getLatestAuthRequestBySubjectAndClient, arg.Subject, arg.ClientID)
	var i OidcAuthRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.ResponseType,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Subject,
		&i.UserEmail,
		&i.AuthTime,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, token, auth_time, audience, subject, application_id, scopes, expires_at, created_at FROM oidc_refresh_tokens
WHERE token = ? AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (OidcRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i OidcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.AuthTime,
		&i.Audience,
		&i.Subject,
		&i.ApplicationID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAccessToken = `-- name: InsertAccessToken :exec
INSERT INTO oidc_access_tokens (id, application_id, subject, audience, scopes, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAccessTokenParams struct {
	ID            string    `json:"id"`
	ApplicationID string    `json:"application_id"`
	Subject       string    `json:"subject"`
	Audience      string    `json:"audience"`
	Scopes        string    `json:"scopes"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) InsertAccessToken(ctx context.Context, arg InsertAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertAccessToken,
		arg.ID,
		arg.ApplicationID,
		arg.Subject,
		arg.Audience,
		arg.Scopes,
		arg.ExpiresAt,
	)
	return err
}

const insertAuthCode = `-- name: InsertAuthCode :exec
INSERT INTO oidc_codes (code, auth_request_id) VALUES (?, ?)
`

type InsertAuthCodeParams struct {
	Code          string `json:"code"`
	AuthRequestID string `json:"auth_request_id"`
}

func (q *Queries) InsertAuthCode(ctx context.Context, arg InsertAuthCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertAuthCode, arg.Code, arg.AuthRequestID)
	return err
}

const insertAuthRequest = `-- name: InsertAuthRequest :exec
INSERT INTO oidc_auth_requests (id, client_id, redirect_uri, scopes, state, nonce, response_type, code_challenge, code_challenge_method)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuthRequestParams struct {
	ID                  string `json:"id"`
	ClientID            string `json:"client_id"`
	RedirectUri         string `json:"redirect_uri"`
	Scopes              string `json:"scopes"`
	State               string `json:"state"`
	Nonce               string `json:"nonce"`
	ResponseType        string `json:"response_type"`
	CodeChallenge       string `json:"code_challenge"`
	CodeChallengeMethod string `json:"code_challenge_method"`
}

func (q *Queries) InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertAuthRequest,
		arg.ID,
		arg.ClientID,
		arg.RedirectUri,
		arg.Scopes,
		arg.State,
		arg.Nonce,
		arg.ResponseType,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO oidc_refresh_tokens (id, token, auth_time, audience, subject, application_id, scopes, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRefreshTokenParams struct {
	ID            string    `json:"id"`
	Token         string    `json:"token"`
	AuthTime      time.Time `json:"auth_time"`
	Audience      string    `json:"audience"`
	Subject       string    `json:"subject"`
	ApplicationID string    `json:"application_id"`
	Scopes        string    `json:"scopes"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.ID,
		arg.Token,
		arg.AuthTime,
		arg.Audience,
		arg.Subject,
		arg.ApplicationID,
		arg.Scopes,
		arg.ExpiresAt,
	)
	return err
}
