// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings.sql

package dbgen

import (
	"context"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT subject, settings, created_at, updated_at FROM user_settings
WHERE subject = ?
`

func (q *Queries) GetUserSettings(ctx context.Context, subject string) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, subject)
	var i UserSetting
	err := row.Scan(
		&i.Subject,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :exec
INSERT INTO user_settings (subject, settings)
VALUES (?, ?)
ON CONFLICT(subject) DO UPDATE SET
    settings = excluded.settings,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertUserSettingsParams struct {
	Subject  string `json:"subject"`
	Settings string `json:"settings"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSettings, arg.Subject, arg.Settings)
	return err
}
